import { parsePassingSiteswap } from "./passing_notation.js";

export const PASSING_PATTERNS = [
  {
    id: "pair-cascades",
    label: "two 3-cascades",
    people: 2,
    arrangement: "circle",
    source: "<3|3>",
    job: "self",
  },
  {
    id: "six-ultimate",
    label: "6-club ultimate",
    people: 2,
    arrangement: "circle",
    source: "<3p|3p>",
    job: "1-count",
  },
  {
    id: "five-two-count",
    label: "5-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 2|2 3p>",
    job: "2-count",
  },
  {
    id: "six-two-count",
    label: "6-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 3|3p 3>",
    job: "2-count",
  },
  {
    id: "six-three-count",
    label: "6-club 3-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 3 3|3p 3 3>",
    job: "3-count",
  },
  {
    id: "six-four-count",
    label: "6-club 4-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 3 3 3|3p 3 3 3>",
    job: "4-count",
  },
  {
    id: "six-five-count",
    label: "6-club 5-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 3 3 3 3|3p 3 3 3 3>",
    job: "5-count",
  },
  {
    id: "six-six-count",
    label: "6-club 6-count",
    people: 2,
    arrangement: "circle",
    source: "<3p 3 3 3 3 3|3p 3 3 3 3 3>",
    job: "6-count",
  },
  {
    id: "six-pps",
    label: "6-club PPS",
    people: 2,
    arrangement: "circle",
    source: "<3p 3p 3|3p 3p 3>",
    job: "PPS",
  },
  {
    id: "six-psp",
    label: "6-club PSP",
    people: 2,
    arrangement: "circle",
    source: "<3p 3 3p|3p 3 3p>",
    job: "PSP",
  },
  {
    id: "six-sps",
    label: "6-club SPS",
    people: 2,
    arrangement: "circle",
    source: "<3 3p 3|3 3p 3>",
    job: "SPS",
  },
  {
    id: "six-spp",
    label: "6-club SPP",
    people: 2,
    arrangement: "circle",
    source: "<3 3p 3p|3 3p 3p>",
    job: "SPP",
  },
  {
    id: "six-left-double",
    label: "6-club left-hand double",
    people: 2,
    arrangement: "circle",
    source: "<4p|3><2|3p>",
    job: "insert",
  },
  {
    id: "four-ultimate",
    label: "4-club ultimate",
    people: 2,
    arrangement: "circle",
    source: "<2p|2p>",
    job: "1-count",
  },
  {
    id: "four-hold",
    label: "4-club hold",
    people: 2,
    arrangement: "circle",
    source: "<2|2>",
    job: "hold",
  },
  {
    id: "two-one-count",
    label: "2-club 1-count",
    people: 2,
    arrangement: "circle",
    source: "<1p|1p>",
    job: "1-count",
  },
  {
    id: "three-two-count",
    label: "3-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<1p 2|2 1p>",
    job: "2-count",
  },
  {
    id: "four-two-count-zips",
    label: "4-club 2-count with zips",
    people: 2,
    arrangement: "circle",
    source: "<2p 2|2p 2>",
    job: "2-count",
  },
  {
    id: "four-pps-zips",
    label: "4-club PPS with zips",
    people: 2,
    arrangement: "circle",
    source: "<2p 2p 2|2p 2p 2>",
    job: "PPS",
  },
  {
    id: "four-four-count-zips",
    label: "4-club 4-count with zips",
    people: 2,
    arrangement: "circle",
    source: "<2p 2 2 2|2p 2 2 2>",
    job: "4-count",
  },
  {
    id: "four-flash",
    label: "4-club flash",
    people: 2,
    arrangement: "circle",
    source: "<4 0|4 0>",
    job: "flash",
  },
  {
    id: "seven-one-count",
    label: "7-club 1-count",
    people: 2,
    arrangement: "circle",
    source: "<4p|3p>",
    job: "1-count",
  },
  {
    id: "seven-two-count",
    label: "7-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<R|L><4xp|3><3|4xp>",
    job: "2-count",
  },
  {
    id: "seven-four-count-doubles",
    label: "7-club 4-count doubles",
    people: 2,
    arrangement: "circle",
    source: "<5p 3 3 3|3 3 5p 3>",
    job: "4-count",
  },
  {
    id: "six-left-single-mux",
    label: "6-club left-hand single",
    people: 2,
    arrangement: "circle",
    source: "<2|3p><2p|3><[3p/2]|3p><3|3>",
    job: "insert",
  },
  {
    id: "eight-two-count",
    label: "8-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<4p 4|4p 4>",
    job: "2-count",
  },
  {
    id: "eight-three-count",
    label: "8-club 3-count",
    people: 2,
    arrangement: "circle",
    source: "<4p 4 4|4p 4 4>",
    job: "3-count",
  },
  {
    id: "eight-four-count",
    label: "8-club 4-count",
    people: 2,
    arrangement: "circle",
    source: "<4p 4 4 4|4p 4 4 4>",
    job: "4-count",
  },
  {
    id: "eight-pps",
    label: "8-club PPS",
    people: 2,
    arrangement: "circle",
    source: "<4p 4p 4|4p 4p 4>",
    job: "PPS",
  },
  {
    id: "eight-psp",
    label: "8-club PSP",
    people: 2,
    arrangement: "circle",
    source: "<4p 4 4p|4p 4 4p>",
    job: "PSP",
  },
  {
    id: "eight-ultimate",
    label: "8-club ultimate",
    people: 2,
    arrangement: "circle",
    source: "<4p|4p>",
    job: "1-count",
  },
  {
    id: "eight-mux",
    label: "8-club multiplex 3p/2",
    people: 2,
    arrangement: "circle",
    source: "<[3p/2]|3p>",
    job: "multiplex",
  },
  {
    id: "nine-two-count",
    label: "9-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<5p 4|4 5p>",
    job: "2-count",
  },
  {
    id: "ten-two-count",
    label: "10-club 2-count",
    people: 2,
    arrangement: "circle",
    source: "<5p 5|5p 5>",
    job: "2-count",
  },
  {
    id: "triangle-one-count",
    label: "9-club triangle 1-count",
    people: 3,
    arrangement: "circle",
    source: "<3p2|3p3|3p1>",
    job: "1-count",
  },
  {
    id: "triangle-three-ones",
    label: "3-club triangle 1-count",
    people: 3,
    arrangement: "circle",
    source: "<1p2|1p3|1p1>",
    job: "1-count",
  },
  {
    id: "triangle-zips",
    label: "6-club triangle with zips",
    people: 3,
    arrangement: "circle",
    source: "<2p2|2p3|2p1><2|2|2>",
    job: "2-count",
  },
  {
    id: "triangle-two-count",
    label: "9-club triangle 2-count",
    people: 3,
    arrangement: "circle",
    source: "<3p2|3p3|3p1><3|3|3>",
    job: "2-count",
  },
  {
    id: "triangle-three-count",
    label: "9-club triangle 3-count",
    people: 3,
    arrangement: "circle",
    source: "<3p2|3p3|3p1><3|3|3><3|3|3>",
    job: "3-count",
  },
  {
    id: "triangle-four-count",
    label: "9-club triangle 4-count",
    people: 3,
    arrangement: "circle",
    source: "<3p2|3p3|3p1><3|3|3><3|3|3><3|3|3>",
    job: "4-count",
  },
  {
    id: "triangle-two-way-three-count",
    label: "9-club triangle two-way 3-count",
    people: 3,
    arrangement: "circle",
    source: "<3p2|3p3|3p1><3|3|3><3|3|3><3p3|3p1|3p2><3|3|3><3|3|3>",
    job: "3-count",
  },
  {
    id: "feed-gorilla",
    label: "9-club gorilla",
    people: 3,
    arrangement: "feed",
    source: "<3p2 3p3|3p1 3|3 3p1>",
    job: "feed",
  },
  {
    id: "feed-nine",
    label: "9-club feed 2-count to 4-counts",
    people: 3,
    arrangement: "feed",
    source: "<3p2 3 3p3 3|3p1 3 3 3|3 3 3p1 3>",
    job: "feed",
  },
  {
    id: "feed-three-count",
    label: "9-club feed 3-count to 6-counts",
    people: 3,
    arrangement: "feed",
    source: "<3p2 3 3 3p3 3 3|3p1 3 3 3 3 3|3 3 3 3p1 3 3>",
    job: "feed",
  },
  {
    id: "box-two-count",
    label: "12-club box 2-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p1|3p4|3p3><3|3|3|3>",
    job: "2-count",
  },
  {
    id: "box-three-count",
    label: "12-club box 3-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p1|3p4|3p3><3|3|3|3><3|3|3|3>",
    job: "3-count",
  },
  {
    id: "box-four-count",
    label: "12-club box 4-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p1|3p4|3p3><3|3|3|3><3|3|3|3><3|3|3|3>",
    job: "4-count",
  },
  {
    id: "circle-two-count",
    label: "12-club circle 2-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p3|3p4|3p1><3|3|3|3>",
    job: "2-count",
  },
  {
    id: "circle-three-count",
    label: "12-club circle 3-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p3|3p4|3p1><3|3|3|3><3|3|3|3>",
    job: "3-count",
  },
  {
    id: "circle-four-count",
    label: "12-club circle 4-count",
    people: 4,
    arrangement: "circle",
    source: "<3p2|3p3|3p4|3p1><3|3|3|3><3|3|3|3><3|3|3|3>",
    job: "4-count",
  },
  {
    id: "line-feed-four",
    label: "12-club line feed 2-count to 6-counts",
    people: 4,
    arrangement: "feed",
    source: "<3p2 3 3p3 3 3p4 3|3p1 3 3 3 3 3|3 3 3p1 3 3 3|3 3 3 3 3p1 3>",
    job: "feed",
  },
  {
    id: "pentagon-three-count",
    label: "15-club pentagon 3-count",
    people: 5,
    arrangement: "circle",
    source: "<3p2|3p3|3p4|3p5|3p1><3|3|3|3|3><3|3|3|3|3>",
    job: "3-count",
  },
];

export function arrangementForSource(source) {
  const parsed = parsePassingSiteswap(source);
  if (parsed.bodyCount < 3) {
    return "circle";
  }
  const feederTargets = new Set();
  parsed.throws[0].forEach((multiplex) => {
    multiplex.forEach((token) => {
      if (token.pass && token.passTarget !== null) {
        feederTargets.add(token.passTarget);
      }
    });
  });
  return feederTargets.size >= 2 ? "feed" : "circle";
}

export function patternById(id) {
  const pattern = PASSING_PATTERNS.find((entry) => entry.id === id);
  if (pattern === undefined) {
    throw new Error(`unknown passing pattern: ${id}`);
  }
  return pattern;
}
